apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: todo-microservice
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'todo-microservice'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - todo-microservice
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: todo-microservice
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            replacement: $1:8080
